version: "3.4"

services:
  pwa: &pwa
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}:${APP_BUILD}
    build: pwa
    depends_on:
      - php
    ports:
      - "81:80"

  php: &php
    image: ghcr.io/conductionnl/commonground-gateway-php:latest
    depends_on:
      - db
    volumes:
      - ./gateway:/srv/api/fixtures:rw,cached
      - ./certs:/var/certs:rw,cached
    environment:
      - DATABASE_URL=postgres://api-platform:!ChangeMe!@db/api?serverVersion=10.1
      #      - DATABASE_URL=mysql://api-platform:!ChangeMe!@db/api?serverVersion=10.1
      - AUTH_ENABLED=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_REPRO=example
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_CACHE=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "82:80"

  api: &nginx
    image: ghcr.io/conductionnl/commonground-gateway-nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=php
      - NGINX_ENV=${APP_ENV}

  # MySQL database:
  #    db:
  #        image: mysql:5.7
  #        environment:
  #            - MYSQL_ROOT_PASSWORD=example
  #            - MYSQL_DATABASE=api
  #            - MYSQL_USER=api-platform
  #            - MYSQL_PASSWORD=!ChangeMe!
  #        volumes:
  #            - db-mysql:/var/lib/mysql:rw
  #        ports:
  #            - "3366:3306"

  #  Postgres db:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  redis:
    image: redis:4-alpine

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

volumes:
  db-data: {}
  uc-data: {}
  db-mysql: {}
