apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
data:
  {{- if .Values.gateway.enabled }}
  gateway-location: https://{{ .Values.ingress.hostname }}
  {{- else }}
  gateway-location: {{ .Values.gateway.location }}
  {{- end }}
  properties: |-
    window.GATSBY_ME_URL = "{{ .Values.pwa.meUrl }}"
    window.GATSBY_API_URL = "{{ .Values.pwa.apiUrl }}";
    window.GATSBY_ADMIN_URL = "{{ .Values.pwa.adminUrl }}";
    window.GATSBY_BASE_URL = "{{ .Values.pwa.baseUrl }}";
    window.GATSBY_FRONTEND_URL = "{{ .Values.pwa.frontendUrl }}";
    window.GATSBY_ORGANIZATION = "{{ .Values.pwa.organization }}";
    window.GATSBY_LOGIN_REDIRECT = "{{ .Values.pwa.redirectUrl }}";
