/**
 *
 * @param schema: form schema generated by the gateway
 * @param data: form data generated by react-hook-form
 * @param object: objectEntity, if editing
 */
export const mutateObjectFormData = (schema: any, data: any, object?: any) => {
  const objectValues: any[] = [];

  Object.entries(data).forEach(([key, _value], idx) => {
    const value = _value as any;

    const attribute = schema.attributes[schema.attributes.findIndex((a: any) => a.name === key)];

    if (!attribute) return;

    const objectValue: any = {
      attribute: `/admin/attributes/${attribute.id}`,
      stringValue: `${value}`, // syntax is intended; always needs to be a string
      id: object?.objectValues[idx].id,
    };

    /**
     * Whenever the .type !== string we need to push the actual value to objectValue
     * The stringValue declared above, is required in any and all types
     */
    if (value) {
      switch (attribute.type) {
        case "string":
          // already set; do nothing
          break;
        case "integer":
          objectValue.integerValue = parseInt(value, 10);
          break;
        default: // development purposes
          console.log(attribute.type);
          break;
      }
    }

    objectValues.push(objectValue);
  });

  const objects = schema.attributes.filter((a: any) => a.type === "object");

  return {
    entity: `/admin/entities/${schema.id}`,
    objectValues,
    objects: objects.map((o: any) => `/admin/object_entities/${o.id}`),
  };
};
