apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-11T11:14:21.7384193+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.1
    description: A Helm chart for Kubernetes
    digest: 61176b210c41b7f1153021924af204988fb50a0dbef2ed51856d5b98543078f7
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.7.tgz
    version: 0.1.7
  skeleton-app:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-10-11T11:14:21.7097279+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.7
    description: A Helm chart for the Skeleton Gatsby Application
    digest: a5068b9436d7b91a6a89104632a07b1146a495f94ee38a128a9f6105b1dbdda6
    name: skeleton-app
    type: application
    urls:
    - skeleton-app-0.1.1.tgz
    version: 0.1.1
  skeleton-pip:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-10-11T11:14:21.7236357+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.7
    description: A Helm chart for the Skeleton Gatsby Application
    digest: 5950d3089a7b74bca5e648c8a87170bfe96b92b39c76847ec5db71a52975b532
    name: skeleton-pip
    type: application
    urls:
    - skeleton-pip-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-11T11:14:21.6941212+02:00"
